name: Render Notebooks for GitHub

on:
  push:
    paths:
      - '**.ipynb'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  render-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}  # Explicitly checkout the branch that triggered the workflow

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbconvert jupyter

      - name: Run conversion script
        run: python .github/workflows/convert_notebooks.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain **/*.ipynb)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Show modified files
        if: steps.git-check.outputs.has_changes == 'true'
        run: git status

      - name: Commit and push changes to current branch
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"
          
          # Add, commit, and push changes
          git add "**/*.ipynb"
          git commit -m "Render notebooks for GitHub compatibility"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${CURRENT_BRANCH}
