name: Render for GitHub

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - '**.ipynb'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  render-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbconvert jupyter

      - name: Configure Git 
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Render notebooks for GitHub
        run: python .github/workflows/render_notebooks.py

      - name: Commit changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.event.pull_request.head.ref }}
            git pull --rebase origin ${{ github.event.pull_request.head.ref }} || echo "No rebase needed"
            git add "**/*.ipynb"
            git commit -m "Render notebooks for GitHub compatibility" || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            git add "**/*.ipynb"
            git commit -m "Render notebooks for GitHub compatibility" || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push origin ${{ github.ref_name }}
          fi
